playerArsenal = [
	//uniforms
	"SC_Uniform_Black",
	"SC_Uniform_Gloves_Black",
	"SC_Uniform_Short_Black",
	"SC_Uniform_Green",
	"SC_Uniform_Gloves_Green",
	"SC_Uniform_Short_Green",
	"SC_Uniform_Tan",
	"SC_Uniform_Gloves_Tan",
	"SC_Uniform_Short_Tan",
	//vests
	"SC_Vest_WD_Basic_Black",
	"SC_Vest_WD_Basic_Desert",
	"SC_Vest_WD_Basic_Green",
	"SC_Vest_WD_Basic_Guard",
	"SC_Vest_WD_Basic_Snow",
	"SC_Vest_WD_Basic_Urban",
	//helms
	"SC_Helmet_WD_Black_V",
	"SC_Helmet_WD_Desert_V",
	"SC_Helmet_WD_Green_V",
	"SC_Helmet_WD_Guard_V",
	"SC_Helmet_WD_Snow_V",
	"SC_Helmet_WD_Urban_V",
	//backpacks
	"SC_Backpack_WD_Black",
	"SC_Backpack_WD_Black_SL",
	"SC_Backpack_WD_Desert",
	"SC_Backpack_WD_Desert_SL",
	"SC_Backpack_WD_Green",
	"SC_Backpack_WD_Green_SL",
	"SC_Backpack_WD_Guard",
	"SC_Backpack_WD_Guard_SL",
	"SC_Backpack_WD_Snow",
	"SC_Backpack_WD_Snow_SL",
	"SC_Backpack_WD_Urban",
	"SC_Backpack_WD_Urban_SL",
	//primary
	"SC_Rifle_AR12C",
	"sc_reflex_chevron_r",
	"optic_aco_grn_smg",
	"optic_aco_smg",
	"optic_aco_grn",
	"optic_aco",
	"acc_pointer_ir",
	"acc_flashlight",
	"SC_35Rnd_762x51_Mag",
	//secondary
	"ACE_Flashlight_Maglite_ML300L",
	"OPTRE_M319s",
	"3Rnd_UGL_FlareGreen_F",
	"3Rnd_UGL_FlareRed_F",
	"3Rnd_UGL_FlareWhite_F",
	"3Rnd_UGL_FlareYellow_F",
	"3Rnd_SmokeBlue_Grenade_shell",
	"3Rnd_SmokeGreen_Grenade_shell",
	"3Rnd_SmokeOrange_Grenade_shell",
	"3Rnd_SmokePurple_Grenade_shell",
	"3Rnd_SmokeRed_Grenade_shell",
	"3Rnd_SmokeWhite_Grenade_shell",
	"3Rnd_SmokeYellow_Grenade_shell",
	"3Rnd_HE_Grenade_shell",
	//launcher
	"SC_MPML",
	"sc_mpml_scope",
	"SC_MPML_M_AT",
	"SC_MPML_M_HE",
	"SC_MPML_M_AA",
	//left-hand extras
	"ItemMap",
	"ItemGPS",
	"B_UavTerminal",
	"TFAR_anprc152",
	"ItemCompass",
	"ItemWatch",
	"OPTRE_Smartfinder",
	"OPTRE_NVG",
	//grenades
	"SmokeShell",
	"SmokeShellBlue",
	"SmokeShellGreen",
	"SmokeShellOrange",
	"SmokeShellPurple",
	"SmokeShellRed",
	"SmokeShellYellow",
	"ACE_Chemlight_HiBlue",
	"ACE_Chemlight_HiGreen",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_UltraHiOrange",
	"ACE_Chemlight_IR",
	"OPTRE_M8_Flare_Blue",
	"OPTRE_M8_Flare_Green",
	"OPTRE_M8_Flare",
	"OPTRE_M8_Flare_White",
	"OPTRE_M8_Flare_Yellow",
	"SC_IG3",
	"ACE_M84",
	"OPTRE_ELB47_Strobe",
	//foam?
	"C7_Remote_Mag",
	//"magazines"
	"murshun_cigs_cigpack",
	"murshun_cigs_lighter",
	"immersion_pops_poppack",
	"acex_intelitems_notepad",
	//misc items
	"ACE_adenosine",
	"ACE_Banana",
	"ACE_fieldDressing",
	"Dermal_Repair_Matrix",
	"ACE_elasticBandage",
	"Space_Bandaid",
	"ACE_packingBandage",
	"ACE_quikclot",
	"White_Goo",
	"ACE_bodyBag",
	"ACE_CableTie",
	"Casualty_Stim",
	"Combat_Stim_A",
	"Combat_Stim_X",
	"ACE_DefusalKit",
	"ACE_EntrenchingTool",
	"ACE_epinephrine",
	"ACE_IR_Strobe_Item",
	"ACE_Flashlight_XL50",
	"ACE_MapTools",
	"MineDetector",
	"ACE_morphine",
	"Space_Painkiller",
	"diw_armor_plates_main_plate",
	"ACE_plasmaIV",
	"ACE_plasmaIV_500",
	"ACE_plasmaIV_250",
	"ACE_rope6",
	"ACE_rope18",
	"ACE_rope36",
	"ACE_splint",
	"ACE_surgicalKit",
	"ToolKit",
	"ACE_tourniquet"
];

//FUNCTIONS

makeArsenal = {
  params ["_jackShack"];

  [_jackShack, playerArsenal] call ace_arsenal_fnc_initBox;

  _jackShack addAction ["Jack Shack Arsenal", {[(_this select 0), player] call ace_arsenal_fnc_openBox;},[],1.5,true,true,"","true",5,false,"",""];
  //_jackShack addAction["Save Current Loadout as Respawn Loadout",saveLoadout,[],1.5,true,true,"","true",5,false,"",""];
  //_jackShack addAction["Toggle Loadout Autosave",toggleLoadoutAutosave,[],1.5,true,true,"","true",5,false,"",""];
	//_jackShack addAction["Empty Aluminator",areWeDoneYet,[],1.5,true,true,"","true",5,false,"",""];

};
